/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.SinhVien;

import java.util.List;
import javax.swing.JOptionPane;
import model.FakeData;
import model.SinhVienLop;

/**
 *
 * @author HP
 */
public class ChiTietDonMuaLop extends javax.swing.JDialog {

    private SinhVienLop svl;
    private boolean isModeAdd;
    private List<SinhVienLop> dssv;
    private SinhVienLop selectedObject;
    
    public ChiTietDonMuaLop(java.awt.Frame parent, boolean modal, List<SinhVienLop> dssv, SinhVienLop selectedObject) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        loadKhoaIntoComboBox();
        this.dssv = dssv;
        this.selectedObject = selectedObject;
    }
    
    public ChiTietDonMuaLop(java.awt.Frame parent, boolean modal, List<SinhVienLop> dssv) {
        super(parent, modal);
        initComponents();
        loadKhoaIntoComboBox();
        this.dssv = dssv;
    }
    
    private void loadKhoaIntoComboBox() {
        List<String> dsTenKhoa = FakeData.layDSKhoa();
        cboKhoa.removeAllItems();
        for (String tenKhoa : dsTenKhoa) {
            cboKhoa.addItem(tenKhoa);
        }
    }
    
    //thiết lập chế độ thêm mới
    public void setAddMode() {
        isModeAdd = true;
        btnThemMoi.setVisible(true);
        btnLuu.setVisible(true);
    }
    
    //thiết lập chế độ sửa
    public void setEditMode() {
        isModeAdd = false;
        btnThemMoi.setVisible(false);
        btnLuu.setVisible(true);
    }
    
    public boolean isCheck(){
        if(txtMaSV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã sinh viên!", "Message", JOptionPane.INFORMATION_MESSAGE);
            txtMaSV.requestFocus();
            return false;
        }
        if(txtTenSV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên sinh viên!", "Message", JOptionPane.ERROR_MESSAGE);
            txtTenSV.requestFocus();
            return false;
        }
        
        return true;
    }
    
    public boolean isCheck_MaSV(){
        String maSV = txtMaSV.getText();
        boolean tonTai = dssv.stream()
                        .anyMatch(sv -> sv.getMaSV().equals(maSV));
        if(tonTai) {
            JOptionPane.showMessageDialog(this, "Sinh viên đã tồn tại trong danh sách!", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    public SinhVienLop getSVL() {
        return svl;
    }
    
    public void setSinhVien(SinhVienLop sv) {
        txtMaSV.setText(sv.getMaSV());
        txtTenSV.setText(sv.getTenSV());
        String tenKhoa = sv.getTenKhoa();
        for (int i = 0; i < cboKhoa.getItemCount(); i++) {
            if (cboKhoa.getItemAt(i).equals(tenKhoa)) {
                cboKhoa.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        cboKhoa = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã sinh viên: ");

        jLabel2.setText("Tên sinh viên: ");

        jLabel3.setText("Khoa: ");

        cboKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSV)
                            .addComponent(txtTenSV)
                            .addComponent(cboKhoa, 0, 229, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnThemMoi)
                    .addComponent(btnLuu))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(isCheck_MaSV()) {
            svl = new SinhVienLop(txtMaSV.getText(), txtTenSV.getText(), cboKhoa.getSelectedItem().toString());
            selectedObject.setMaSV(svl.getMaSV());
            selectedObject.setTenSV(svl.getTenSV());
            selectedObject.setTenKhoa(svl.getTenKhoa());
            
            dispose();
        } else svl = null;
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        if(isCheck() && isCheck_MaSV()) {
            svl = new SinhVienLop(txtMaSV.getText(), txtTenSV.getText(), cboKhoa.getSelectedItem().toString());
            dispose();
        }else svl = null;
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonMuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonMuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonMuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietDonMuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChiTietDonMuaLop dialog = new ChiTietDonMuaLop(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JComboBox<String> cboKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
